# Repo: https://github.com/themefisher/educenter-hugo
# Docs: https://docs.gethugothemes.com/educenter/

######################## default configuration ####################
baseURL = "https://praba-slcfhr.netlify.app/"
title = "SLCFHR - Helping the helpless!"
theme = "codechilli-lukxmi-ayurveda"
timeZone = "Asia/Colombo"

# Post Pagination
paginate = 6 # see https://gohugo.io/extras/pagination/

# Post Excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/

# Disqus Comments Widget
disqusShortname = "" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/

# Language Config
disableLanguages = [] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### Default Parameters ################################
[params]
logo_light = "images/logo-light.svg"
logo_dark = "images/logo-dark.svg"

# Meta Data
description = "Sri Lakxmi Centre for Human Rehabilitation managed by Dr. P. Shivapadasundaram (Dr.Shiva) - Government Registration number GA-00283455"
author = "Praba Ponnambalam"

# Contact Details
address = "336/1 Kelanitissa Mawatha<br>Wanawanasala, Kelaniya<br>Sri Lanka 11600"
mobile = "+94 766 266 332"
call = "+94766266332"
whatsapp = "0094766266332"
email = "reach@lakxmiayurveda.lk"
map_location = "https://maps.app.goo.gl/V8WJndskCJixqWd97"

# Form Action
contact_form_action = "#" # contact form works with https://formspree.io

# Google Tag Manager
google_tag_manager = "GTM-NC2T6MN"

# Top Header
top_header = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true

# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# Google Maps
[params.map]
enable = true
gmap_api = "AIzaSyD3Kp0KhTjg6jvuM1LOCZ18S7Z05WWK8TM" #6.979777816573666, 79.89603197786164
map_latitude = "6.979777816573666"
map_longitude = "79.89603197786164"
map_marker = "images/marker.png" # marker size 200*300 px

# Cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[Languages.en.params]
home = "Home"

# copyright
copyright = "&copy; <a href=\"/\">Siri Lakxmi Centre for Human Rehabilitation<sup>&reg;</sup></a> 2023-{year}. Reg No GA-00283455."

################### English navigation ####################

# Header Nav
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[Languages.en.menu.main]]
name = "Events"
url = "event/"
weight = 2

[[Languages.en.menu.main]]
name = "Blog"
url = "blog/"
weight = 3
  
[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 4

[[Languages.en.menu.main]]
name = "Donate"
url = "donate/"
weight = 5

# [[Languages.en.menu.main]]
# weight = 6
# name = "Pages"
# hasChildren = true

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "teacher"
#   url = "teacher/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "notice"
#   url = "notice/"

# footer menu

[[Languages.en.menu.footer]]
name = "Privacy Policy"
url = "privacy-plocy/"

[[Languages.en.menu.footer]]
name = "Terms & Conditions"
url = "terms/"

[[Languages.en.menu.footer]]
name = "Media Releases"
url = "media/"

[[Languages.en.menu.footer]]
name = "Notice Board"
url = "notice/"

[[Languages.en.menu.footer]]
name = "FAQ"
url = "faq/"